baseURL = 'https://iainfoclub.netlify.app/blog'
languageCode = 'fr-fr'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "Le club"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "à propos"
    weight = 1
    url = "about"

[params]
author = "Club Informatique"
user = "IA"
hostname = "groupe-gema"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/ClubInformatiqueIASchoollyon"


[[params.social]]
key = 2
name = "linkedin"
url = ""

[[params.social]]
key = 3
name = "email"
url = "mailto:marc.garnier-de-boisgrollier.edu@groupe-gema.com"
